exercise_40 = [
    "Diaphragmatic breathing",
    "Meditation with breathing control",
    "Child's pose (Balasana)",
    "Legs up the wall",
    "Seated forward fold",
    "Cat-Cow pose",
    "Side stretch while seated",
    "Gentle spinal twist on the floor",
    "Shoulder rolls",
    "Neck stretches",
    "Seated arm stretch",
    "Hip circles",
    "Guided meditation",
    "Lying back relaxation",
    "Breathing exercise 4-7-8",
    "Lower back stretch on the mat",
    "Hamstring stretch",
    "Ankle rotations",
    "Wrist mobility stretch",
    "Gentle yoga flow"
]
exercise_60 = [
    "Marching in place",
    "Side steps with arm swings",
    "Shoulder mobility rotations",
    "Standing knee lifts",
    "Dynamic hip circles",
    "Slow squats",
    "Standing calf raises",
    "Arm circles",
    "Wall push-ups",
    "Walking around the room",
    "Standing side bends",
    "Cat-Cow from tabletop position",
    "Gentle yoga sun salutation",
    "Glute bridge",
    "Chair squats",
    "Dynamic hamstring stretch",
    "Leg swings front and back",
    "Resistance band arm pulls",
    "Light Pilates routine",
    "Slow dancing or step touch"
]
exercise_80 = [
    "Brisk walking indoors or on treadmill",
    "Bodyweight squats",
    "Alternating lunges",
    "Step-ups on low platform or stair",
    "Knee push-ups",
    "Plank hold",
    "Glute bridges",
    "Side leg raises",
    "Standing kickbacks",
    "Wall sit",
    "Jumping jacks (slow pace)",
    "Mountain climbers (slow)",
    "Resistance band rows",
    "Sumo squats",
    "Pilates roll-ups",
    "Marching with high knees (slow)",
    "Shoulder taps in plank",
    "Standing oblique crunches",
    "Seated Russian twists (no weight)",
    "Light shadow boxing"
]
exercise_100 = [
    "Jogging in place",
    "Standard push-ups",
    "Burpees without jump",
    "Jumping jacks (normal pace)",
    "Bodyweight lunges",
    "Squats with small jump",
    "Mountain climbers (moderate pace)",
    "Step-ups on chair or step",
    "Plank shoulder taps",
    "High knees (moderate)",
    "Kettlebell swings (light weight)",
    "Dumbbell deadlifts (light)",
    "Wall sit with arm raises",
    "Side plank hold",
    "Sumo squat pulses",
    "Alternating step lunges",
    "Triceps dips on chair",
    "Standing punches (shadow boxing)",
    "Core twist with light dumbbell",
    "Jump rope (slow pace)"
]
exercise_120 = [
    "Jump rope (steady pace)",
    "Burpees with jump",
    "Mountain climbers (fast pace)",
    "Jump squats",
    "Jumping lunges",
    "Push-ups with shoulder tap",
    "Kettlebell swings (moderate)",
    "High knees (fast)",
    "Jumping jacks (fast)",
    "Box step jumps (low surface)",
    "Shadow boxing combo",
    "Squat to press (dumbbells)",
    "Skater jumps",
    "Tabata 20/10 circuit (bodyweight)",
    "Lateral shuffle steps",
    "Plank jacks",
    "Dumbbell thrusters (light)",
    "Fast step-ups",
    "Burpee + push-up combo",
    "Tuck jumps (low height)"
]
exercise_140 = [
    "HIIT circuit (20s work / 10s rest)",
    "Jump squats (fast)",
    "Burpees (max effort)",
    "Jumping lunges (explosive)",
    "High knees sprint in place",
    "Mountain climbers (maximum speed)",
    "Push-ups with clap",
    "Double unders (jump rope)",
    "Fast skater jumps",
    "Box jumps (stable low surface)",
    "Sprint in place",
    "Plank to squat jumps",
    "Battle rope simulation (with towel)",
    "Kettlebell clean and press",
    "Tabata with bodyweight exercises",
    "Jump lunge to squat combo",
    "Explosive side-to-side hops",
    "Fast shadow boxing",
    "Jump rope (double speed)",
    "Burpees with jump and push-up"
]
exercise_160 = [
    "Sprint in place (maximum effort)",
    "Burpees with jump and tuck",
    "Jump squats (max effort)",
    "Jump lunges (fast)",
    "High knees (maximum speed)",
    "Tabata HIIT 20/10 full body",
    "Mountain climbers (max speed)",
    "Jump rope (maximum tempo)",
    "Explosive push-ups",
    "Skater jumps (fast pace)",
    "Squat jumps to floor touch",
    "Jump lunge to jump squat combo",
    "Fast plank jacks",
    "Shadow boxing sprint",
    "Burpees with push-up and jump",
    "Fast alternating step-ups",
    "Lateral hops over object",
    "Sprint interval: 20s on / 10s off",
    "Tuck jumps",
    "High-intensity Tabata circuit"
]
